version: '3'
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=gautam
      - MONGO_PASSWORD=admin
      - SESSION_SECRET=mysecret
    command: npm run dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: gautam
      MONGO_INITDB_ROOT_PASSWORD: admin
      
